#!/bin/sh -e

# Will store the built package's files to
# allow us to cherry-pick the ICU related files.
mkdir -p tmp
export DESTDIR="$PWD/tmp"

meson \
    --prefix= \
    -Dglib=enabled \
    -Dicu=enabled \
    -Dicu_builtin=false \
    -Dbenchmark=disabled \
    -Dcairo=disabled \
    -Ddocs=disabled \
    . output

ninja -C output
ninja -C output install

install -Dt "$1/lib"              tmp/lib/libharfbuzz-icu*
install -Dt "$1/lib/pkgconfig"    tmp/lib/pkgconfig/harfbuzz-icu.pc
install -Dt "$1/include/harfbuzz" tmp/include/harfbuzz/hb-icu.h
