#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Denable-docs=false \
    -Denable-x11=false \
    -Denable-wayland=true \
    -Denable-xkbregistry=false \
    . output

ninja -C output
ninja -C output install
