#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/ \
    -Denable-docs=false \
    -Denable-x11=false \
    -Dxkb-config-root=/share/X11/xkb \
    -Dxkb-locale-root=/share/X11/locale \
    -Denable-wayland=true \
    -Denable-xkbregistry=false \
    . output

ninja -C output
ninja -C output install
