#!/bin/sh -e

./configure \
    --prefix= \
    --sbindir=/bin \
    --enable-iproute2 \
    --enable-pkcs11 \
    --enable-plugins \
    --enable-password-save \
    --enable-x509-alt-username \
    --disable-plugin-auth-pam

make
make DESTDIR="$1" install
