#!/bin/sh -e

# Setup base directories.
for d in boot dev etc home mnt var sucks; do
    install -dm 755 "$1/$d"
done

install -dm 555  "$1/proc"
install -dm 555  "$1/sys"
install -dm 0750 "$1/root"
install -dm 1777 "$1/tmp"

# Setup manpages directories.
for d in 1 2 3 4 5 6 7 8; do
    install -dm 755 "$1/share/man/man$d"
done

# Add symlinks.
ln -s / "$1/usr"
ln -s bin "$1/sbin"

# Setup /var.
for d in cache local opt log/old lib/misc empty service run lock; do
    install -dm 755 "$1/var/$d"
done

install -dm 1777 "$1/var/tmp"
install -dm 1777 "$1/var/spool/mail"

ln -s spool/mail  "$1/var/mail"

# /etc skeleton files.
for f in fstab group host.conf hosts issue os-release \
         passwd profile securetty shells mime.types; do
    install -m 644 "$f" "$1/etc"
done

for f in crypttab shadow; do
    install -m 600 "$f" "$1/etc"
done

ln -s /proc/self/mounts "$1/etc/mtab"
