#!/bin/sh -e

# This gets rid of the check for ada on my machine at least won't pass this
sed -i '5357,5381d' configure

./configure \
    --prefix=/usr \
    --build=x86_64-pc-linux-musl \
    --host=x86_64-pc-linux-musl \
    --enable-targets=x86_64-pep \
    --disable-gold \
    --enable-ld=no \
    --enable-plugins \
    --disable-multilib \
    --disable-werror \
    --disable-nls \
    --disable-gprof \
    --with-mmap \
    --with-system-zlib \
    --enable-libada=no

make all-gas

make DESTDIR="$1" install-gas
