#!/bin/sh -e

machine=$(cc -dumpmachine)

./configure \
    --prefix=// \
    --sbindir=/bin \
    --build="$machine" \
    --host="$machine" \
    --with-crypto_backend=gcrypt \
    --disable-blkid

make
make DESTDIR="$1" install
