#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/usr/etc

make
make DESTDIR="$1" install

install -Dm 755 update-certdata.sh "$1/usr/etc/ssl"

# Link ca-certificates to cert.pem
ln -sfv ../cert.pem "$1/usr/etc/ssl/certs/ca-certificates.crt"
