#!/bin/sh -e

./configure \
    --prefix=/ \
    --sbindir=/bin \
    --sysconfdir=/etc \
    --rundir=/var/run \
    --libexecdir=/lib/dhcpcd

make
make DESTDIR="$1" install

# Install runit service.
install -Dm 755 dhcpcd.run        "$1/etc/sv/dhcpcd/run"
ln -s /var/run/runit/supervise.dhcpcd "$1/etc/sv/dhcpcd/supervise"
