#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/ \
    --sysconfdir=/etc \
    --mandir=/share/man \
    -Ddocs=false \
    -Dintrospection=false \
    . output

ninja -C output
ninja -C output install
