#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX="/" \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_C_FLAGS="-I/include/harfbuzz" \
    -DCMAKE_CXX_FLAGS="-I/include/harfbuzz"

cmake --build build
cmake --install build
