#!/bin/sh -e

patch -p1 < fix-musl.patch

# Remove gettext requirement.
sed -i 's/ngettext/printf/g' Tools/MiniBrowser/gtk/BrowserDownloadsBar.c
sed -i '/po_files \*\.po/d'  Source/WebCore/platform/gtk/po/CMakeLists.txt
sed -i '/^GETTEXT_C/d'       Source/WebCore/platform/gtk/po/CMakeLists.txt

export DESTDIR="$1"

mkdir build
cd build

#    -DCMAKE_BUILD_TYPE=MinRelSize \
#Jit only works on some architectures
#Many of these are personal preference and aren't needed afaik. Such as mediasource, video, audio, opengl, wpe, woff2, openjpeg. However I believe the following may be vital however not 100% sure.
#Web Crypto
#Do not use wpe if you are on wayland
cmake -GNinja \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_INSTALL_DIR=/usr/lib \
    -DPORT=GTK \
    -DENABLE_WAYLAND_TARGET=ON \
    -DCMAKE_SKIP_RPATH=ON \
    -DENABLE_BUBBLEWRAP_SANDBOX=OFF \
    -DENABLE_SAMPLING_PROFILER=OFF \
    -DENABLE_GEOLOCATION=OFF \
    -DENABLE_INTROSPECTION=OFF \
    -DENABLE_INTL=OFF \
    -DENABLE_SPELLCHECK=OFF \
    -DENABLE_VIDEO=ON \
    -DENABLE_WEBGL=OFF \
    -DENABLE_WEB_AUDIO=ON \
    -DUSE_LIBHYPHEN=OFF \
    -DUSE_LIBNOTIFY=OFF \
    -DUSE_LIBSECRET=OFF \
    -DUSE_OPENJPEG=OFF \
    -DUSE_WOFF2=OFF \
    -DUSE_WPE_RENDERER=ON \
    -DUSE_SYSTEMD=OFF \
    -DENABLE_WEB_CRYPTO=ON \
    -DENABLE_MEDIASOURCE=ON \
    -DUSE_LD_GOLD=OFF \
    ..

ninja
ninja install

