#!/bin/sh -e

./configure \
    --prefix=/ \
    --mandir=/share/man \
    --enable-pc-files \
    --disable-rpath-hack \
    --with-pkg-config-libdir=/lib/pkgconfig \
    --with-shared \
    --enable-widec \
    --without-ada \
    --without-tests \
    --without-debug \
    --without-cxx-binding

make
make DESTDIR="$1" install

# Force ncurses to link against wide-character ncurses library.
for lib in ncurses form panel menu; do
    rm -f "$1/lib/lib${lib}.so"
    printf '%s\n' "INPUT(-l${lib}w)" > "$1/lib/lib${lib}.so"
    chmod 755 "$1/lib/lib${lib}.so"
    ln -sf "lib${lib}w.a" "$1/lib/lib${lib}.a"
done

# Some packages look for libcurses instead of libncurses when building.
printf '%s\n' "INPUT(-lncursesw)" > "$1/lib/libcursesw.so"
ln -s libncurses.so "$1/lib/libcurses.so"

# Some programs don't find the proper headers for some reason so we
# Will just symlink them ourselves
ln -s /include/ncursesw/*.h "$1/include/"

#Fix pkgconfig file.
ln -s ncursesw.pc "$1/lib/pkgconfig/ncurses.pc"
