#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Dhas-dlvsym=false \
    -Dglx=no \
    -Dx11=false \
    -Degl=yes \
    . output

ninja -C output
ninja -C output install
