#!/bin/sh -e

export DESTDIR="$1"

sed -i '/\<sys\/sysctl\>/d' src/cpHastySpace.c

cmake -B build \
    -DCMAKE_INSTALL_PREFIX="/usr" \
    -DCMAKE_INSTALL_LIBDIR=lib

cmake --build build
cmake --install build
