#!/bin/sh -e

export DESTDIR="$1"

sed -i '/\<sys\/sysctl\>/d' src/cpHastySpace.c

cmake -B build \
    -DCMAKE_INSTALL_PREFIX="/" \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_DEMOS=OFF

cmake --build build
cmake --install build
