#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX="" \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_LIBDIR=/lib \
    -DBUILD_SHARED_LIBS=True

cmake --build   build
cmake --install build
