#!/bin/sh -e

./configure \
    --prefix= \
    --localstatedir=/var \
    --bindir=/bin \
    --sbindir=/bin \
    --libdir=/lib \
    --enable-libuuid \
    --enable-libblkid \
    --enable-fsck \
    --disable-makeinstall-chown \
    --disable-rpath \
    --without-udev \
    --without-python \
    --without-systemd

make
make DESTDIR="$1" install

# Fix broken --sbindir.
mv -f "$1/sbin/"* "$1/bin"
rmdir "$1/sbin"
