#!/bin/sh -e

tar xvf 935d223be5454015526bb5ca2258dd8cca71bc7d
#tar xvf bfbe82e2064635ce57dceb2581c514bdff6fc12b
#cd flatwhatson-emacs-bfbe82e
cd masm11-emacs-935d223

# This removes the section that causes an error with no icons
sed -i '/No icon/d' src/xfns.c
sed -i '/No icon/d' src/pgtkfns.c
sed -i '1475d' src/xfns.c
sed -i '1511d' src/xfns.c
sed -i '555d' src/pgtkfns.c
sed -i '586d' src/pgtkfns.c

./autogen.sh
./configure \
    --prefix=/usr \
    --with-modules \
    --with-xft \
    --with-pgtk \
    --with-cairo \
    --without-toolkit-scroll-bars \
    --without-dbus \
    --without-gconf \
    --with-gsettings \
    --with-xpm=no \
    --with-gnutls=yes \
    --without-makeinfo \
    --with-nativecomp \
    --with-json=yes

mkdir -p "$1/usr/share/emacs/site-lisp"
cat << EOF > "$1/usr/share/emacs/site-lisp/site-start.el"
;; Better security defaults
(with-eval-after-load 'gnutls
  (setq
   gnutls-verify-error t
   gnutls-min-prime-bits 2048
   gnutls-trustfiles '("/etc/ssl/cert.pem")))

;; Needed unless KISS Linux gains librsvg support
(setq-default shr-blocked-images ".*\.svg$")
EOF

make
make DESTDIR="$1" install

rm -rf "$1/usr/lib/systemd"
