#!/bin/sh -e

# Disable building 'cairo-sphinx'.
sed -i "s/BUILD_SPHINX_TRUE=/BUILD_SPHINX_TRUE='#'/"   configure
sed -i "s/BUILD_SPHINX_FALSE='#'/BUILD_SPHINX_FALSE=/" configure

# Disable building tests.
sed -i 's/test perf//g' Makefile.in

#If you don't need gtk you can disable gobject to avoid glib for cairo

./configure \
    --prefix=/usr \
    --disable-static \
    --enable-tee \
    --enable-glesv2 \
    --enable-egl \
    --disable-trace \
    --disable-valgrind \
    --disable-gtk-doc-html \
    --enable-gobject

make
make DESTDIR="$1" install
