#!/bin/sh -e

pkg_dir=$1

make CC="${CC:-cc}"
make USRDIR=/ DESTDIR="$1" ZICDIR=/bin install

set -- africa asia australasia europe northamerica southamerica

./zic -d "$pkg_dir/share/zoneinfo" "$@"
./zic -d "$pkg_dir/share/zoneinfo/posix" "$@"
./zic -d "$pkg_dir/share/zoneinfo/right" -L leapseconds "$@"
./zic -d "$pkg_dir/share/zoneinfo" -p America/New_York
