#!/bin/sh -e

export DESTDIR="$1"

meson \
	--prefix=/ \
	. build

ninja -C build
ninja -C build install

chmod a+s "$1/bin/swaylock"

rm -rf "$1/share/zsh/"
rm -rf "$1/share/fish/"
rm -rf "$1/share/bash-completion/"
rm -rf "$1/etc/pam.d/"
