#!/bin/sh -e

./configure \
    --prefix= \
    --libexecdir=/bin \
    --localstatedir=/var \
    --disable-dbus

make
make DESTDIR="$1" install

# Install runit service.
install -Dm755 eiwd.run         "$1/etc/sv/eiwd/run"
ln -s /var/run/runit/supervise.eiwd "$1/etc/sv/eiwd/supervise"
