#!/bin/sh -e

# Remove 'atk-bridge' dependency which removes the 'dbus' dependency.
#sed -i 's/ATK_PACKAGES="atk atk-bridge-2.0"/ATK_PACKAGES="atk"/' \
#    configure

#sed -i '/<atk-bridge.h>/d;/atk_bridge_adaptor_init/d' \
#    gtk/a11y/gtkaccessibility.c

# Don't build GTK examples/demos/testsuite.
#sed -i 's/demos tests testsuite examples//' Makefile.am Makefile.in
#sed -i 's/docs m4macros/m4macros/'          Makefile.am Makefile.in

export DESTDIR="$1"

meson \
	--prefix=/ \
	-Dx11-backend=false \
	-Dwayland-backend=true \
	-Dprint=none \
	-Dxinerama=disabled \
	-Dintrospection=false \
	-Ddemos=false \
	-Dbuild-examples=false \
	-Dbuild-tests=false \
	-Dvulkan=disabled \
	-Dmedia=none \
	. build

ninja -C build
ninja -C build install

# We don't compile with librsvg which leads to this
# utility solely causing compiler errors for some
# packages. It has no use at all.
rm -f "$1/bin/gtk-encode-symbolic-svg"
