#!/bin/sh -e

./configure \
    --prefix=/ \
    --syslibdir=/lib

make
make DESTDIR="$1" install

mkdir -p "$1/bin"
ln -s  /lib/ld-musl-x86_64.so.1 "$1/bin/ldd"

# Fix incorrect symlink to libc.so.
ln -sf libc.so "$1/lib/ld-musl-x86_64.so.1"

# Install BSD compatibility headers.
install -Dm 755 cdefs.h "$1/include/sys/cdefs.h"
install -Dm 755 queue.h "$1/include/sys/queue.h"
install -Dm 755 tree.h  "$1/include/sys/tree.h"

# Install getconf.
cc getconf.c -o "$1/bin/getconf"
cc getent.c  -o "$1/bin/getent"
