#!/bin/sh -e

export DESTDIR="$1"

mkdir -p subprojects
( cd subprojects; git clone https://codeberg.org/dnkl/tllist.git; git clone https://codeberg.org/dnkl/fcft.git )

meson \
    --prefix=/ \
    --buildtype=release \
    . output

ninja -C output
ninja -C output install
