#!/bin/sh -e

patch -p1 < cmake-no-execinfo.patch

if kiss l cmake; then
    export DESTDIR="$1"

    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/ \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_USE_SYSTEM_CURL=True \
        -DCMAKE_USE_SYSTEM_EXPAT=True \
        -DCMAKE_USE_SYSTEM_ZLIB=True \
        -DCMAKE_USE_SYSTEM_BZIP2=True \
        -DBUILD_TESTING=OFF

    cmake --build   build
    cmake --install build

else
    ./configure \
        --prefix=/ \
        --system-curl \
        --system-expat \
        --system-zlib \
        --system-bzip2

    make
    make DESTDIR="$1" install
fi

rm -rf "$1/doc"
rm -rf "$1/share/cmake"*/Help
