#!/bin/sh -e

make CC="${CC:-cc} -static"

install -Dm755 pigz   "$1/bin/pigz"
install -Dm755 unpigz "$1/bin/unpigz"
install -Dm644 pigz.1 "$1/share/man/man1/pigz.1"

ln -sf pigz   "$1/bin/gzip"
ln -sf pigz   "$1/bin/zcat"
ln -sf unpigz "$1/bin/gunzip"
ln -sf pigz.1 "$1/share/man/man1/gzip.1"
