#!/bin/sh -e

patch -p1 < makefile.patch
patch -p1 < configure.patch

( cd src; patch -p1 < ../makefilesrc.patch )

autoreconf --verbose --force --install

./configure \
	--prefix=/

make

install -Dm755 src/gammastep "$1/bin/gammastep"
