#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --with-screen=ncursesw \
    --with-ssl \
    --enable-gopher \
    --with-zlib \
    --enable-ipv6

make
make DESTDIR="$1" install
