#!/bin/sh -e

./configure \
    --prefix=/ \
    --disable-static \
    --enable-shared \
    ac_cv_func_malloc_0_nonnull=yes \
    ac_cv_func_realloc_0_nonnull=yes

make
make DESTDIR="$1" install

ln -s flex "$1/bin/lex"
