#!/bin/sh -e

export LDFLAGS="-rdynamic"

./configure \
    --prefix=/ \
    --enable-cscope \
    --enable-multibyte \
    --with-ex-name=vim-ex \
    --with-view-name=vim-view \
    --disable-perlinterp \
    --disable-rubyinterp \
    --disable-netbeans \
    --disable-gpm \
    --disable-hangulinput \
    --disable-xim \
    --disable-gui \
    --disable-nls \
    --without-x \
    --enable-python3interp=yes

make
make DESTDIR="$1" install
