#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Avoid repeating ourselves.
mk() {
    make \
        libdir=/lib/ \
        bindir=/bin/ \
        mandir=/share/man/ \
        includedir=/include/ \
        "$@"
}

mk CC="${CC:-cc}"
mk DESTDIR="$1" install
