--- Makefile.am
+++ Makefile.am
@@ -1,12 +1,12 @@
 
-SUBDIRS = src po
+SUBDIRS = src
 ACLOCAL_AMFLAGS = -I m4
 
 # Install systemd user unit files locally for distcheck
-DISTCHECK_CONFIGURE_FLAGS = \
-	--with-systemduserunitdir=$$dc_install_base/$(systemduserunitdir)
+#DISTCHECK_CONFIGURE_FLAGS = \
+#	--with-systemduserunitdir=$$dc_install_base/$(systemduserunitdir)
 
-UPDATE_ICON_CACHE = gtk-update-icon-cache -f -t $(datadir)/icons/hicolor || :
+#UPDATE_ICON_CACHE = gtk-update-icon-cache -f -t $(datadir)/icons/hicolor || :
 
 EXTRA_ROOTDOC_FILES = \
 	CONTRIBUTING.md \
@@ -15,24 +15,24 @@
 	README-colorramp \
 	gammastep.conf.sample
 
-_HICOLOR_FILES = \
-	data/icons/hicolor/scalable/apps/gammastep.svg \
-	data/icons/hicolor/scalable/apps/gammastep-status-on.svg \
-	data/icons/hicolor/scalable/apps/gammastep-status-off.svg
+#_HICOLOR_FILES = \
+#	data/icons/hicolor/scalable/apps/gammastep.svg \
+#	data/icons/hicolor/scalable/apps/gammastep-status-on.svg \
+#	data/icons/hicolor/scalable/apps/gammastep-status-off.svg
 
-DESKTOP_IN_FILES = \
-	data/applications/gammastep.desktop.in \
-	data/applications/gammastep-indicator.desktop.in
+#DESKTOP_IN_FILES = \
+#	data/applications/gammastep.desktop.in \
+#	data/applications/gammastep-indicator.desktop.in
 
-SYSTEMD_USER_UNIT_IN_FILES = \
-	data/systemd/gammastep.service.in \
-	data/systemd/gammastep-indicator.service.in
+#SYSTEMD_USER_UNIT_IN_FILES = \
+	#data/systemd/gammastep.service.in \
+	#data/systemd/gammastep-indicator.service.in
 
-APPDATA_IN_FILES = \
-	data/appdata/gammastep-indicator.appdata.xml.in
+#APPDATA_IN_FILES = \
+	#data/appdata/gammastep-indicator.appdata.xml.in
 
-APPARMOR_IN_FILES = \
-	data/apparmor/com.gitlab.chinstrap.gammastep.in
+#APPARMOR_IN_FILES = \
+#	data/apparmor/com.gitlab.chinstrap.gammastep.in
 
 
 # Icons
@@ -57,10 +57,10 @@
 
 # We would preferable use @INTLTOOL_DESKTOP_RULE@ here but
 # sadly it is broken for out-of-tree builds.
-%.desktop: %.desktop.in $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po)
-	$(AM_V_GEN)$(MKDIR_P) $(@D);
-	$(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -d -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
-	rm -f -- $(top_builddir)/po/.intltool-merge-cache.lock
+#%.desktop: %.desktop.in $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po)
+#	$(AM_V_GEN)$(MKDIR_P) $(@D);
+#	$(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -d -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
+#	rm -f -- $(top_builddir)/po/.intltool-merge-cache.lock
 endif
 
 
@@ -85,10 +85,10 @@
 
 # We would preferable use @INTLTOOL_XML_RULE@ here but
 # sadly it is broken for out-of-tree builds.
-%.xml: %.xml.in $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po)
-	$(AM_V_GEN)$(MKDIR_P) $(@D);
-	$(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -x -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
-	rm -f -- $(top_builddir)/po/.intltool-merge-cache.lock
+#%.xml: %.xml.in $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po)
+#	$(AM_V_GEN)$(MKDIR_P) $(@D);
+#	$(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -x -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
+#	rm -f -- $(top_builddir)/po/.intltool-merge-cache.lock
 endif
 
 
@@ -118,8 +118,3 @@
 	$(appdata_DATA) \
 	$(apparmor_DATA)
 
-
-# Update PO translations
-.PHONY: update-po
-update-po:
-	cd po && $(MAKE) POTFILES gammastep.pot update-po
