#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib

cd build

make

install -Dm 755 ccache       "$1/bin/ccache"
install -Dm 644 doc/ccache.1 "$1/share/man/man1/ccache.1"

mkdir -p "$1/lib/ccache/bin"

host=$(cc -dumpmachine)

for link in cc gcc g++ cpp c++ \
            "$host-cc" "$host-gcc" "$host-g++" "$host-cpp" "$host-c++"; do
    ln -sf /bin/ccache "$1/lib/ccache/bin/$link"
done
