#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

kinstall() {
    mkdir -p "${3%/*}"; cp "$2" "$3"
    chmod "$1" "$3"
}

make

# Build static binary for bearssl, word splitting on CFLAGS is intentional.
# shellcheck disable=2086
"${CC:-cc}" \
    -static $CFLAGS \
    -I ./inc \
    -include tools/brssl.h \
    tools/*.c \
    build/libbearssl.a \
    -o brssl


kinstall 755 brssl               "$1/usr/bin/brssl"
kinstall 644 build/libbearssl.a  "$1/usr/lib/libbearssl.a"
kinstall 755 build/libbearssl.so "$1/usr/lib/libbearssl.so"

mv inc "$1/usr/include"
