#!/bin/sh -e

# Remove incorrect bash dependency.
sed -i 's/bash/sh/' install-sh

./configure \
    --prefix=/ \
    --sbindir=/bin \
    --disable-gettext

make
make \
    DIST_ROOT="$1" \
    PKG_ROOT_SBIN_DIR=/bin \
    PKG_ROOT_LIB_DIR=/lib \
    install
