#!/bin/sh -e

./configure \
    --prefix=/ \
    --sbindir=/bin \
    --with-udev-rules-dir=/lib/udev/rules.d \
    --disable-alsaconf \
    --disable-bat \
    --disable-xmlto \
    --disable-nls

make
make DESTDIR="$1" install
